[2023-11-04T15:39:25.839+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=data_ingestion_gcs_dag/run_id=manual__2023-11-04T15:39:15.863838+00:00/task_id=local_to_gcs_task permission to 509
[2023-11-04T15:39:25.878+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=data_ingestion_gcs_dag/run_id=manual__2023-11-04T15:39:15.863838+00:00/task_id=local_to_gcs_task permission to 509
[2023-11-04T15:39:25.911+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2023-11-04T15:39:15.863838+00:00 [queued]>
[2023-11-04T15:39:25.924+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2023-11-04T15:39:15.863838+00:00 [queued]>
[2023-11-04T15:39:25.925+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-04T15:39:25.941+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2023-11-04 15:39:15.863838+00:00
[2023-11-04T15:39:25.952+0000] {standard_task_runner.py:57} INFO - Started process 120 to run task
[2023-11-04T15:39:25.955+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'manual__2023-11-04T15:39:15.863838+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpt66puyb3']
[2023-11-04T15:39:25.958+0000] {standard_task_runner.py:85} INFO - Job 37: Subtask local_to_gcs_task
[2023-11-04T15:39:25.972+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:193: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-11-04T15:39:26.006+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=data_ingestion_gcs_dag/run_id=manual__2023-11-04T15:39:15.863838+00:00/task_id=local_to_gcs_task permission to 509
[2023-11-04T15:39:26.011+0000] {task_command.py:416} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2023-11-04T15:39:15.863838+00:00 [running]> on host 78e1cd38ebdc
[2023-11-04T15:39:26.086+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='local_to_gcs_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-04T15:39:15.863838+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-04T15:39:15.863838+00:00'
[2023-11-04T15:39:34.144+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-04T15:39:34.155+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20231104T153915, start_date=20231104T153925, end_date=20231104T153934
[2023-11-04T15:39:34.188+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-04T15:39:34.211+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
